project_id = "inkwweudpaszunmfnogq"

[functions.manage-users]
verify_jwt = false

[functions.check-task-deadlines]
verify_jwt = false

[functions.meta-capi-event]
verify_jwt = false

[functions.tiktok-capi-event]
verify_jwt = false

[functions.meta-lead-webhook]
verify_jwt = false

[functions.generate-task-guide]
verify_jwt = false

[functions.whatsapp-api]
verify_jwt = false

[functions.generate-capture-page]
verify_jwt = false

[functions.generate-proposal]
verify_jwt = false
