project_id = "inkwweudpaszunmfnogq"

[functions.manage-users]
verify_jwt = false

[functions.check-task-deadlines]
verify_jwt = false

[functions.meta-capi-event]
verify_jwt = false

[functions.tiktok-capi-event]
verify_jwt = false
